version: '3.7'

services:

    react:
        container_name: Eventing-Frontend
        image: eventingfront
        ports: 
            - 5000:8080
        environment: 
            - CHOKIDAR_USEPOLLING=true
        depends_on: 
            - express

    express:
        container_name: Eventing-Backend
        image: eventingback
        ports: 
            - 3000:8000
        environment: 
            - CHOKIDAR_USEPOLLING=true