version: '3.7'

services:

    redis:
        image: redis
        container_name: redis
        expose: 
            - 6379

    express:
        container_name: Eventing-Backend
        image: eventingback:dev
        ports: 
            - 5000:5000
        environment: 
            - CHOKIDAR_USEPOLLING=true
        links:
            - redis

    
            
            